name: Build Windows Vulkan (.exe)

on:
  workflow_dispatch:

jobs:
  build-windows-vulkan:
    runs-on: windows-2022

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Get Latest Vulkan SDK Version
      shell: powershell
      id: get_vulkan_version
      run: |
        $version = (curl.exe -s https://vulkan.lunarg.com/sdk/latest/windows.txt).Trim()
        echo "VULKAN_VERSION=$version" >> $env:GITHUB_ENV
        echo "Mendeteksi Vulkan SDK versi: $version"

    - name: Download and Install Vulkan SDK Directly
      shell: powershell
      run: |
        echo "Downloading Vulkan SDK ${{ env.VULKAN_VERSION }} dari LunarG..."
        curl.exe -L -o vulkan-sdk-installer.exe "https://sdk.lunarg.com/sdk/download/${{ env.VULKAN_VERSION }}/windows/vulkan-sdk.exe"
        
        echo "Installing Vulkan SDK (Silent Mode)..."
        # Menjalankan installer dan mengunci proses agar GitHub WAJIB menunggu sampai selesai total
        $proc = Start-Process -FilePath .\vulkan-sdk-installer.exe -ArgumentList "--default-answer", "--accept-licenses", "--confirm-command", "install" -PassThru
        $proc | Wait-Process
        
        # Mendaftarkan path lokasi instalasi default asli LunarG
        echo "VULKAN_SDK=C:\VulkanSDK\${{ env.VULKAN_VERSION }}" >> $env:GITHUB_ENV
        echo "C:\VulkanSDK\${{ env.VULKAN_VERSION }}\Bin" >> $env:GITHUB_PATH

    - name: Configure CMake
      shell: powershell
      run: |
        # Memastikan folder target memang ada sebelum CMake berjalan
        if (!(Test-Path "$env:VULKAN_SDK")) {
            echo "Eror: Folder Vulkan SDK tidak ditemukan di $env:VULKAN_SDK"
            exit 1
        }
        
        cmake -B build -G "Visual Studio 17 2022" -A x64 `
          -DGGML_NATIVE=OFF `
          -DGGML_VULKAN=ON `
          -DLLAMA_BUILD_TESTS=OFF `
          -DGGML_BACKEND_DL=ON `
          -DGGML_CPU_ALL_VARIANTS=ON `
          -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: |
        cmake --build build --config Release --parallel

    - name: Pack and Upload Artifacts (.exe & .dll)
      uses: actions/upload-artifact@v4
      with:
        name: llama-cpp-turboquant-vulkan-win64
        path: |
          build/bin/Release/*.exe
          build/bin/Release/*.dll
